#!/bin/bash

# IMAGE_NAME var comes from docker hub
# https://docs.docker.com/docker-hub/builds/advanced/#environment-variables-for-building-and-testing

docker build \
    --build-arg CREATED=`date -u -Iseconds` \
    --build-arg REVISION=`git rev-parse --short HEAD` \
    -t ${IMAGE_NAME} .